### ISSUE TITLE
Failed to create catalog manager

### ISSUE THREAD

**Issue by MachaelLee** [CeresDB/ceresdb#315] opened 2022-10-18 11:47 UTC
### Describe this problem

Panic with the stacktrace:
```
2022-10-18 16:01:56.037 ERRO [common_util/src/panic.rs:42] thread 'main' panicked 'Failed to create catalog manager: VisitSysCatalog { source: VisitorOpenTable { source: Unexpected { source: OperateByWriteWorker { space_id: 7, table: "BIZ_643000197_INFLUENCE_DEFAULT", table_id: TableId(7696581394717), source: Channel { source: ReadWal { source: Read { source: "Corruption: block checksum mismatch: expected 3149814890, got 3226198023  in /home/admin/data/ceresdbx/wal/263234.sst offset 30618826 size 1260", backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateBacktrace>::generate
             at /home/chunshao.rcs/github/CeresDB/ceresdb/wal/src/manager.rs:26:21
      <wal::manager::error::Read as snafu::IntoError<wal::manager::error::Error>>::into_error
             at /home/chunshao.rcs/github/CeresDB/ceresdb/wal/src/manager.rs:26:21
      <core::result::Result<T,E> as snafu::ResultExt<T,E>>::context::{{closure}}
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.6.10/src/lib.rs:318:30
      core::result::Result<T,E>::map_err
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/result.rs:855:27
      <core::result::Result<T,E> as snafu::ResultExt<T,E>>::context
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.6.10/src/lib.rs:318:9
      <wal::rocks_impl::manager::RocksLogIterator as wal::manager::BlockingLogIterator>::next_log_entry
             at /home/chunshao.rcs/github/CeresDB/ceresdb/wal/src/rocks_impl/manager.rs:569:25
   1: <wal::manager::BatchLogIteratorAdapter as wal::manager::BatchLogIterator>::next_log_entries::{{closure}}::{{closure}}
             at /home/chunshao.rcs/github/CeresDB/ceresdb/wal/src/manager.rs:320:50
      <tokio::runtime::blocking::task::BlockingT
```

### Steps to reproduce

Have no idea about how to reproduce this panic now.

### Expected behavior

Won't fail.

### Additional Information

maybe this bug similar to #308

**Comment by ShiKaiWi** [comment] 2022-10-26 08:35
This is caused by the corruption of the RocksDB files. Usually, such error will happen when writing to the disk which is already full.

**Comment by ShiKaiWi** [comment] 2022-10-26 08:36
I guess no need to fix this bug because this is caused by RocksDB. Let's close it.

**Closed by ShiKaiWi** 2022-10-26 08:36 UTC
Labels: bug
