### ISSUE TITLE
Support `aarch64-unknown-linux-gnu` target

### ISSUE THREAD

**Issue by waynexia** [CeresDB/ceresdb#63] opened 2022-06-24 07:27 UTC
**Description**

Add support for `aarch64-unknown-linux-gnu`

**Proposal**

Support build on `aarch64-unknown-linux-gnu ` first. Probably add a new CI job to cover this.

Running on this arch is planned but with a lower priority. 

**Additional context**

**Comment by zwpaper** [comment] 2022-07-27 05:55
how can we confirm that a target is supported?

I have an aarch64 mac, I can build and run the CeresDB locally, and it seems that most of the functions work as expected besides an SST error log occurred.

I run the CRUD example on README, and get all the correct responses.

**Comment by ShiKaiWi** [comment] 2022-07-27 06:12
Maybe there are some issues caused by cross compiling to fix if we choose build CeresDB by github actions, e.g. https://github.com/CeresDB/ceresdb-client-py/issues/20.

**Comment by waynexia** [comment] 2022-07-27 06:31
>how can we confirm that a target is supported?

We need to ensure chip, runtime os and dev toolchain are supported. To list a target as "supported" I think there are two steps:
- Have CI to prevent untested regression.
- Have the capacity and willingness to solve problems on that target quickly.
But sadly we don't have these two conditions 😣 So the target is "maybe support", or in other words, is Tire-2 priority compared to amd64-linux

**Comment by zwpaper** [comment] 2022-07-27 11:24
haha, of course, CeresDB should focus on the rapid development currently

**Comment by jiacai2050** [comment] 2023-03-02 13:49
Closing since this issue has been quiet for a while, free free to reopen if others have requirements depending on this.

**Closed by jiacai2050** 2023-03-02 13:49 UTC
Labels: enhancement
