### ISSUE TITLE
Build failed because of these errors! 

### ISSUE THREAD

**Issue by theseusyang** [CeresDB/ceresdb#117] opened 2022-07-21 02:35 UTC
when executing `docker build -t ceresdb .` , these errors happen:

```
Updating crates.io index
#12 38.89     Updating git repository `https://github.com/waynexia/arrow-datafusion.git`
#12 156.5 error: failed to get `datafusion` as a dependency of package `arrow_deps v0.1.0 (/ceresdb/arrow_deps)`
#12 156.5 
#12 156.5 Caused by:
#12 156.5   failed to load source for dependency `datafusion`
#12 156.5 
#12 156.5 Caused by:
#12 156.5   Unable to update https://github.com/waynexia/arrow-datafusion.git?rev=bb3e002a4d89f9a5104bba34511b4c593a9c0d05#bb3e002a
#12 156.5 
#12 156.5 Caused by:
#12 156.5   failed to clone into: /usr/local/cargo/git/db/arrow-datafusion-8f64698f94ffb3e6
#12 156.5 
#12 156.5 Caused by:
#12 156.5   network failure seems to have happened
#12 156.5   if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
#12 156.5   https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
```

**Comment by chunshao90** [comment] 2022-07-21 02:42
Check you network to ensure connecting to github.

**Comment by ShiKaiWi** [comment] 2022-07-21 06:45
@theseusyang This seems not a bug and I will close this issue. Feel free to file new issues if you encounter any other problems.

**Closed by ShiKaiWi** 2022-07-21 06:45 UTC
Labels: bug
