### ISSUE TITLE
Should CeresDB support interface route in No-Meta mode?

### ISSUE THREAD

**Issue by MachaelLee** [CeresDB/ceresdb#702] opened 2023-03-07 08:24 UTC
### Describe This Problem

In With-Meta mode, We can use route interface to query table's location as follow:
```
curl --location --request POST 'http://{CeresMetaAddr}:8080/api/v1/route' \
--header 'Content-Type: application/json' \
--data-raw '{
    "clusterName":"defaultCluster",
    "schemaName":"public",
    "table":["demo"]
}'

```

But there is no one in No-Meta mode.

### Proposal

Should we support interface route in No-Meta mode?

**Comment by ShiKaiWi** [comment] 2023-03-07 08:26
Duplicate of #146

**Comment by ShiKaiWi** [comment] 2023-03-07 08:28
Duplicate of #146

**Comment by MachaelLee** [comment] 2023-03-07 08:54
> If #146 fixed, we can retrieve routing information from CeresDB rather than CeresMeta no matter which mode is chosen.

Yes, I think it is more reasonable to retrieve routing information from CeresDB. It is not necessary for users to be aware of Meta.

**Closed** 2023-03-07 09:52 UTC
Labels: enhancement
